<?php
// /scripts/reset/countries.php

declare(strict_types=1);

use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Database\Schema\Blueprint;
use App\Models\Country;

function resetCountriesTable(): array
{
    $messages = [];
    try {
        $tableName = 'countries';

        // 1. Disable constraints to allow a clean drop/recreate
        Capsule::schema()->disableForeignKeyConstraints();
        Capsule::schema()->dropIfExists($tableName);

        // 2. Create structure matching your CREATE TABLE requirements
        Capsule::schema()->create($tableName, function (Blueprint $table) {
            $table->mediumIncrements('id'); // mediumint(8) unsigned primary key
            $table->string('country', 100);
            $table->char('country_code', 3)->nullable();
            $table->string('currency', 255)->nullable();
            $table->string('currency_symbol', 255)->nullable();
        });

        $messages[] = "created modernized 'countries' table structure.";

        // 3. THE LEGACY DATA ARRAY
        // Format: [id, country, country_code, currency, currency_symbol]
        $legacyData = [
            [1, 'Afghanistan', 'AFG', 'AFN', '؋'],
            [2, 'Aland Islands', 'ALA', 'EUR', '€'],
            [3, 'Albania', 'ALB', 'ALL', 'Lek'],
            [4, 'Algeria', 'DZA', 'DZD', 'دج'],
            [5, 'American Samoa', 'ASM', 'USD', '$'],
            [6, 'Andorra', 'AND', 'EUR', '€'],
            [7, 'Angola', 'AGO', 'AOA', 'Kz'],
            [8, 'Anguilla', 'AIA', 'XCD', '$'],
            [9, 'Antarctica', 'ATA', 'AAD', '$'],
            [10, 'Antigua And Barbuda', 'ATG', 'XCD', '$'],
            [11, 'Argentina', 'ARG', 'ARS', '$'],
            [12, 'Armenia', 'ARM', 'AMD', '֏'],
            [13, 'Aruba', 'ABW', 'AWG', 'ƒ'],
            [14, 'Australia', 'AUS', 'AUD', '$'],
            [15, 'Austria', 'AUT', 'EUR', '€'],
            [16, 'Azerbaijan', 'AZE', 'AZN', 'm'],
            [17, 'Bahamas The', 'BHS', 'BSD', 'B$'],
            [18, 'Bahrain', 'BHR', 'BHD', '.د.ب'],
            [19, 'Bangladesh', 'BGD', 'BDT', '৳'],
            [20, 'Barbados', 'BRB', 'BBD', 'Bds$'],
            [21, 'Belarus', 'BLR', 'BYN', 'Br'],
            [22, 'Belgium', 'BEL', 'EUR', '€'],
            [23, 'Belize', 'BLZ', 'BZD', '$'],
            [24, 'Benin', 'BEN', 'XOF', 'CFA'],
            [25, 'Bermuda', 'BMU', 'BMD', '$'],
            [26, 'Bhutan', 'BTN', 'BTN', 'Nu.'],
            [27, 'Bolivia', 'BOL', 'BOB', 'Bs.'],
            [28, 'Bosnia and Herzegovina', 'BIH', 'BAM', 'KM'],
            [29, 'Botswana', 'BWA', 'BWP', 'P'],
            [30, 'Bouvet Island', 'BVT', 'NOK', 'kr'],
            [31, 'Brazil', 'BRA', 'BRL', 'R$'],
            [32, 'British Indian Ocean Territory', 'IOT', 'USD', '$'],
            [33, 'Brunei', 'BRN', 'BND', 'B$'],
            [34, 'Bulgaria', 'BGR', 'BGN', 'Лв.'],
            [35, 'Burkina Faso', 'BFA', 'XOF', 'CFA'],
            [36, 'Burundi', 'BDI', 'BIF', 'FBu'],
            [37, 'Cambodia', 'KHM', 'KHR', 'KHR'],
            [38, 'Cameroon', 'CMR', 'XAF', 'FCFA'],
            [39, 'Canada', 'CAN', 'CAD', '$'],
            [40, 'Cape Verde', 'CPV', 'CVE', '$'],
            [41, 'Cayman Islands', 'CYM', 'KYD', '$'],
            [42, 'Central African Republic', 'CAF', 'XAF', 'FCFA'],
            [43, 'Chad', 'TCD', 'XAF', 'FCFA'],
            [44, 'Chile', 'CHL', 'CLP', '$'],
            [45, 'China', 'CHN', 'CNY', '¥'],
            [46, 'Christmas Island', 'CXR', 'AUD', '$'],
            [47, 'Cocos (Keeling) Islands', 'CCK', 'AUD', '$'],
            [48, 'Colombia', 'COL', 'COP', '$'],
            [49, 'Comoros', 'COM', 'KMF', 'CF'],
            [50, 'Congo', 'COG', 'XAF', 'FC'],
            [51, 'Democratic Republic of the Congo', 'COD', 'CDF', 'FC'],
            [52, 'Cook Islands', 'COK', 'NZD', '$'],
            [53, 'Costa Rica', 'CRI', 'CRC', '₡'],
            [54, 'Cote D Ivoire (Ivory Coast)', 'CIV', 'XOF', 'CFA'],
            [55, 'Croatia', 'HRV', 'HRK', 'kn'],
            [56, 'Cuba', 'CUB', 'CUP', '$'],
            [57, 'Cyprus', 'CYP', 'EUR', '€'],
            [58, 'Czech Republic', 'CZE', 'CZK', 'Kč'],
            [59, 'Denmark', 'DNK', 'DKK', 'Kr.'],
            [60, 'Djibouti', 'DJI', 'DJF', 'Fdj'],
            [61, 'Dominica', 'DMA', 'XCD', '$'],
            [62, 'Dominican Republic', 'DOM', 'DOP', '$'],
            [63, 'East Timor', 'TLS', 'USD', '$'],
            [64, 'Ecuador', 'ECU', 'USD', '$'],
            [65, 'Egypt', 'EGY', 'EGP', 'ج.م'],
            [66, 'El Salvador', 'SLV', 'USD', '$'],
            [67, 'Equatorial Guinea', 'GNQ', 'XAF', 'FCFA'],
            [68, 'Eritrea', 'ERI', 'ERN', 'Nfk'],
            [69, 'Estonia', 'EST', 'EUR', '€'],
            [70, 'Ethiopia', 'ETH', 'ETB', 'Nkf'],
            [71, 'Falkland Islands', 'FLK', 'FKP', '£'],
            [72, 'Faroe Islands', 'FRO', 'DKK', 'Kr.'],
            [73, 'Fiji Islands', 'FJI', 'FJD', 'FJ$'],
            [74, 'Finland', 'FIN', 'EUR', '€'],
            [75, 'France', 'FRA', 'EUR', '€'],
            [76, 'French Guiana', 'GUF', 'EUR', '€'],
            [77, 'French Polynesia', 'PYF', 'XPF', '₣'],
            [78, 'French Southern Territories', 'ATF', 'EUR', '€'],
            [79, 'Gabon', 'GAB', 'XAF', 'FCFA'],
            [80, 'Gambia The', 'GMB', 'GMD', 'D'],
            [81, 'Georgia', 'GEO', 'GEL', 'ლ'],
            [82, 'Germany', 'DEU', 'EUR', '€'],
            [83, 'Ghana', 'GHA', 'GHS', 'GH₵'],
            [84, 'Gibraltar', 'GIB', 'GIP', '£'],
            [85, 'Greece', 'GRC', 'EUR', '€'],
            [86, 'Greenland', 'GRL', 'DKK', 'Kr.'],
            [87, 'Grenada', 'GRD', 'XCD', '$'],
            [88, 'Guadeloupe', 'GLP', 'EUR', '€'],
            [89, 'Guam', 'GUM', 'USD', '$'],
            [90, 'Guatemala', 'GTM', 'GTQ', 'Q'],
            [91, 'Guernsey and Alderney', 'GGY', 'GBP', '£'],
            [92, 'Guinea', 'GIN', 'GNF', 'FG'],
            [93, 'Guinea-Bissau', 'GNB', 'XOF', 'CFA'],
            [94, 'Guyana', 'GUY', 'GYD', '$'],
            [95, 'Haiti', 'HTI', 'HTG', 'G'],
            [96, 'Heard Island and McDonald Islands', 'HMD', 'AUD', '$'],
            [97, 'Honduras', 'HND', 'HNL', 'L'],
            [98, 'Hong Kong S.A.R.', 'HKG', 'HKD', '$'],
            [99, 'Hungary', 'HUN', 'HUF', 'Ft'],
            [100, 'Iceland', 'ISL', 'ISK', 'kr'],
            [101, 'India', 'IND', 'INR', '₹'],
            [102, 'Indonesia', 'IDN', 'IDR', 'Rp'],
            [103, 'Iran', 'IRN', 'IRR', '﷼'],
            [104, 'Iraq', 'IRQ', 'IQD', 'د.ع'],
            [105, 'Ireland', 'IRL', 'EUR', '€'],
            [106, 'Israel', 'ISR', 'ILS', '₪'],
            [107, 'Italy', 'ITA', 'EUR', '€'],
            [108, 'Jamaica', 'JAM', 'JMD', 'J$'],
            [109, 'Japan', 'JPN', 'JPY', '¥'],
            [110, 'Jersey', 'JEY', 'GBP', '£'],
            [111, 'Jordan', 'JOR', 'JOD', 'ا.د'],
            [112, 'Kazakhstan', 'KAZ', 'KZT', 'лв'],
            [113, 'Kenya', 'KEN', 'KES', 'KSh'],
            [114, 'Kiribati', 'KIR', 'AUD', '$'],
            [115, 'North Korea', 'PRK', 'KPW', '₩'],
            [116, 'South Korea', 'KOR', 'KRW', '₩'],
            [117, 'Kuwait', 'KWT', 'KWD', 'ك.د'],
            [118, 'Kyrgyzstan', 'KGZ', 'KGS', 'лв'],
            [119, 'Laos', 'LAO', 'LAK', '₭'],
            [120, 'Latvia', 'LVA', 'EUR', '€'],
            [121, 'Lebanon', 'LBN', 'LBP', '£'],
            [122, 'Lesotho', 'LSO', 'LSL', 'L'],
            [123, 'Liberia', 'LBR', 'LRD', '$'],
            [124, 'Libya', 'LBY', 'LYD', 'د.ل'],
            [125, 'Liechtenstein', 'LIE', 'CHF', 'CHf'],
            [126, 'Lithuania', 'LTU', 'EUR', '€'],
            [127, 'Luxembourg', 'LUX', 'EUR', '€'],
            [128, 'Macau S.A.R.', 'MAC', 'MOP', '$'],
            [129, 'Macedonia', 'MKD', 'MKD', 'ден'],
            [130, 'Madagascar', 'MDG', 'MGA', 'Ar'],
            [131, 'Malawi', 'MWI', 'MWK', 'MK'],
            [132, 'Malaysia', 'MYS', 'MYR', 'RM'],
            [133, 'Maldives', 'MDV', 'MVR', 'Rf'],
            [134, 'Mali', 'MLI', 'XOF', 'CFA'],
            [135, 'Malta', 'MLT', 'EUR', '€'],
            [136, 'Man (Isle of)', 'IMN', 'GBP', '£'],
            [137, 'Marshall Islands', 'MHL', 'USD', '$'],
            [138, 'Martinique', 'MTQ', 'EUR', '€'],
            [139, 'Mauritania', 'MRT', 'MRO', 'MRU'],
            [140, 'Mauritius', 'MUS', 'MUR', '₨'],
            [141, 'Mayotte', 'MYT', 'EUR', '€'],
            [142, 'Mexico', 'MEX', 'MXN', '$'],
            [143, 'Micronesia', 'FSM', 'USD', '$'],
            [144, 'Moldova', 'MDA', 'MDL', 'L'],
            [145, 'Monaco', 'MCO', 'EUR', '€'],
            [146, 'Mongolia', 'MNG', 'MNT', '₮'],
            [147, 'Montenegro', 'MNE', 'EUR', '€'],
            [148, 'Montserrat', 'MSR', 'XCD', '$'],
            [149, 'Morocco', 'MAR', 'MAD', 'DH'],
            [150, 'Mozambique', 'MOZ', 'MZN', 'MT'],
            [151, 'Myanmar', 'MMR', 'MMK', 'K'],
            [152, 'Namibia', 'NAM', 'NAD', '$'],
            [153, 'Nauru', 'NRU', 'AUD', '$'],
            [154, 'Nepal', 'NPL', 'NPR', '₨'],
            [155, 'Bonaire, Sint Eustatius and Saba', 'BES', 'USD', '$'],
            [156, 'Netherlands', 'NLD', 'EUR', '€'],
            [157, 'New Caledonia', 'NCL', 'XPF', '₣'],
            [158, 'New Zealand', 'NZL', 'NZD', '$'],
            [159, 'Nicaragua', 'NIC', 'NIO', 'C$'],
            [160, 'Niger', 'NER', 'XOF', 'CFA'],
            [161, 'Nigeria', 'NGA', 'NGN', '₦'],
            [162, 'Niue', 'NIU', 'NZD', '$'],
            [163, 'Norfolk Island', 'NFK', 'AUD', '$'],
            [164, 'Northern Mariana Islands', 'MNP', 'USD', '$'],
            [165, 'Norway', 'NOR', 'NOK', 'kr'],
            [166, 'Oman', 'OMN', 'OMR', '.ع.ر'],
            [167, 'Pakistan', 'PAK', 'PKR', '₨'],
            [168, 'Palau', 'PLW', 'USD', '$'],
            [169, 'Palestinian Territory Occupied', 'PSE', 'ILS', '₪'],
            [170, 'Panama', 'PAN', 'PAB', 'B/.'],
            [171, 'Papua new Guinea', 'PNG', 'PGK', 'K'],
            [172, 'Paraguay', 'PRY', 'PYG', '₲'],
            [173, 'Peru', 'PER', 'PEN', 'S/.'],
            [174, 'Philippines', 'PHL', 'PHP', '₱'],
            [175, 'Pitcairn Island', 'PCN', 'NZD', '$'],
            [176, 'Poland', 'POL', 'PLN', 'zł'],
            [177, 'Portugal', 'PRT', 'EUR', '€'],
            [178, 'Puerto Rico', 'PRI', 'USD', '$'],
            [179, 'Qatar', 'QAT', 'QAR', 'ق.ر'],
            [180, 'Reunion', 'REU', 'EUR', '€'],
            [181, 'Romania', 'ROU', 'RON', 'lei'],
            [182, 'Russia', 'RUS', 'RUB', '₽'],
            [183, 'Rwanda', 'RWA', 'RWF', 'FRw'],
            [184, 'Saint Helena', 'SHN', 'SHP', '£'],
            [185, 'Saint Kitts And Nevis', 'KNA', 'XCD', '$'],
            [186, 'Saint Lucia', 'LCA', 'XCD', '$'],
            [187, 'Saint Pierre and Miquelon', 'SPM', 'EUR', '€'],
            [188, 'Saint Vincent And The Grenadines', 'VCT', 'XCD', '$'],
            [189, 'Saint-Barthelemy', 'BLM', 'EUR', '€'],
            [190, 'Saint-Martin (French part)', 'MAF', 'EUR', '€'],
            [191, 'Samoa', 'WSM', 'WST', 'SAT'],
            [192, 'San Marino', 'SMR', 'EUR', '€'],
            [193, 'Sao Tome and Principe', 'STP', 'STD', 'Db'],
            [194, 'Saudi Arabia', 'SAU', 'SAR', '﷼'],
            [195, 'Senegal', 'SEN', 'XOF', 'CFA'],
            [196, 'Serbia', 'SRB', 'RSD', 'din'],
            [197, 'Seychelles', 'SYC', 'SCR', 'SRe'],
            [198, 'Sierra Leone', 'SLE', 'SLL', 'Le'],
            [199, 'Singapore', 'SGP', 'SGD', '$'],
            [200, 'Slovakia', 'SVK', 'EUR', '€'],
            [201, 'Slovenia', 'SVN', 'EUR', '€'],
            [202, 'Solomon Islands', 'SLB', 'SBD', 'Si$'],
            [203, 'Somalia', 'SOM', 'SOS', 'Sh.so.'],
            [204, 'South Africa', 'ZAF', 'ZAR', 'R'],
            [205, 'South Georgia', 'SGS', 'GBP', '£'],
            [206, 'South Sudan', 'SSD', 'SSP', '£'],
            [207, 'Spain', 'ESP', 'EUR', '€'],
            [208, 'Sri Lanka', 'LKA', 'LKR', 'Rs'],
            [209, 'Sudan', 'SDN', 'SDG', '.س.ج'],
            [210, 'Suriname', 'SUR', 'SRD', '$'],
            [211, 'Svalbard And Jan Mayen Islands', 'SJM', 'NOK', 'kr'],
            [212, 'Swaziland', 'SWZ', 'SZL', 'E'],
            [213, 'Sweden', 'SWE', 'SEK', 'kr'],
            [214, 'Switzerland', 'CHE', 'CHF', 'CHf'],
            [215, 'Syria', 'SYR', 'SYP', 'LS'],
            [216, 'Taiwan', 'TWN', 'TWD', '$'],
            [217, 'Tajikistan', 'TJK', 'TJS', 'SM'],
            [218, 'Tanzania', 'TZA', 'TZS', 'TSh'],
            [219, 'Thailand', 'THA', 'THB', '฿'],
            [220, 'Togo', 'TGO', 'XOF', 'CFA'],
            [221, 'Tokelau', 'TKL', 'NZD', '$'],
            [222, 'Tonga', 'TON', 'TOP', '$'],
            [223, 'Trinidad And Tobago', 'TTO', 'TTD', '$'],
            [224, 'Tunisia', 'TUN', 'TND', 'ت.د'],
            [225, 'Turkey', 'TUR', 'TRY', '₺'],
            [226, 'Turkmenistan', 'TKM', 'TMT', 'T'],
            [227, 'Turks And Caicos Islands', 'TCA', 'USD', '$'],
            [228, 'Tuvalu', 'TUV', 'AUD', '$'],
            [229, 'Uganda', 'UGA', 'UGX', 'USh'],
            [230, 'Ukraine', 'UKR', 'UAH', '₴'],
            [231, 'United Arab Emirates', 'ARE', 'AED', 'إ.د'],
            [232, 'United Kingdom', 'GBR', 'GBP', '£'],
            [233, 'United States', 'USA', 'USD', '$'],
            [234, 'United States Minor Outlying Islands', 'UMI', 'USD', '$'],
            [235, 'Uruguay', 'URY', 'UYU', '$'],
            [236, 'Uzbekistan', 'UZB', 'UZS', 'лв'],
            [237, 'Vanuatu', 'VUT', 'VUV', 'VT'],
            [238, 'Vatican City State (Holy See)', 'VAT', 'EUR', '€'],
            [239, 'Venezuela', 'VEN', 'VEF', 'Bs'],
            [240, 'Vietnam', 'VNM', 'VND', '₫'],
            [241, 'Virgin Islands (British)', 'VGB', 'USD', '$'],
            [242, 'Virgin Islands (US)', 'VIR', 'USD', '$'],
            [243, 'Wallis And Futuna Islands', 'WLF', 'XPF', '₣'],
            [244, 'Western Sahara', 'ESH', 'MAD', 'MAD'],
            [245, 'Yemen', 'YEM', 'YER', '﷼'],
            [246, 'Zambia', 'ZMB', 'ZMW', 'ZK'],
            [247, 'Zimbabwe', 'ZWE', 'ZWL', '$'],
            [248, 'Kosovo', 'XKX', 'EUR', '€'],
            [249, 'Curaçao', 'CUW', 'ANG', 'ƒ'],
            [250, 'Sint Maarten (Dutch part)', 'SXM', 'ANG', 'ƒ']
        ];

        // 4. Populate from array
        $count = 0;
        foreach ($legacyData as $row) {
            Country::create([
                'id'              => $row[0],
                'country'         => $row[1],
                'country_code'    => $row[2],
                'currency'        => $row[3],
                'currency_symbol' => $row[4],
            ]);
            $count++;
        }

        $messages[] = "successfully imported $count countries into Gonachi.";
    } catch (\Throwable $e) {
        $messages[] = "countries table error: " . $e->getMessage();
    } finally {
        Capsule::schema()->enableForeignKeyConstraints();
    }

    return $messages;
}
