<?php
// /scripts/reset/faqs.php

declare(strict_types=1);

use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Database\Schema\Blueprint;
use App\Models\Faq;

function resetFaqsTable(): array
{
    $messages = [];

    try {
        $tableName = (new Faq())->getTable();

        Capsule::schema()->dropIfExists($tableName);
        $messages[] = "dropped existing {$tableName} table";

        Capsule::schema()->create($tableName, function (Blueprint $table) {
            $table->increments('id');
            $table->string('question');
            $table->text('answer');
            $table->unsignedInteger('status_id')->default(Faq::STATUS_ACTIVE)->index();
            $table->integer('display_order')->default(0)->index();
            $table->unsignedBigInteger('orig_user_id')->nullable()->index();
            $table->timestamps();

            // Foreign key to users table
            $table->foreign('orig_user_id')->references('id')->on('users')->onDelete('set null');
        });

        $messages[] = "created {$tableName} table";

        // ---------------------------------------------------------
        // Default FAQ entries for Gonachi Real Estate World
        // ---------------------------------------------------------
        $defaultFaqs = [
            // Groups
            ['question' => 'How do I create a group on Gonachi real estate platform?', 'answer' => 'To create a group on Gonachi, follow these steps: Log in to your Gonachi account. Click on the dashboard in the navigation menu and next "Groups" tab. Click on the "Create Group" button. Fill in the required details such as group name, description, and category. Choose the appropriate details for your group. Click on the "Create"/submit button to finish creating your group.'],
            ['question' => 'How many members can I add to my group on Gonachi real estate platform?', 'answer' => 'There is no limit to the number of members you can add to your group on Gonachi.'],
            ['question' => 'Can I customize the settings for my group on Gonachi real estate platform?', 'answer' => 'Yes, you can customize the settings for your group on Gonachi. For example, you can choose to allow members to post or comment on content, or you can limit those privileges to group administrators.'],
            ['question' => 'What types of content can I share in my group on Gonachi real estate platform?', 'answer' => 'You can share various types of content in your group on Gonachi, including text, photos, videos, files and links to external websites. However, please note that any content shared in the group must comply with Gonachis terms of use and community guidelines. You can share contents to individuals in your group and also the ability to share content with users outside of your group.'],
            ['question' => 'How can I promote my group on Gonachi real estate platform?', 'answer' => 'You can promote your group on Gonachi by sharing it on your social media channels, inviting your friends and colleagues to join, and by participating in relevant discussions on the platform. You can also use Gonachis paid Mega advertising options to promote your group to a wider audience.'],

            // View contractor quotations
            ['question' => 'How do I view contractor quotations?', 'answer' => 'To view contractor quotations, you will typically need to receive a response from the contractor on Gonachi. Once you have received the quotations, you can review them to compare costs and determine which contractor is the best fit for your project.'],
            ['question' => 'How do I compare contractor quotations?', 'answer' => 'To compare contractor quotations, it is important to look beyond just the total cost of the project. You should also consider factors such as the contractor\'s experience, their approach to the project, their Gonachi ratings and their timeline for completion. You can also ask for references from past clients to get a sense of the contractor\'s work quality and customer service. When going through and reviewing each contractor’s responses to client\'s quotations request, clients can click on view ratings to see contractor’s overall rating and any reviews that have been left by previous clients. Reviewing individual contractor’s ratings will help the client in decision making regarding contractor of choice. The rating is based on a scale of 1 to 5 stars on different rating criteria, and additional comments. It is recommended that you read several reviews before making a decision about hiring a contractor.'],
            ['question' => 'Can I negotiate the cost of a contractor quotation?', 'answer' => 'Yes, in most cases, you can negotiate the cost of a contractor quotation. However, it is important to keep in mind that the contractor has likely based their estimate on their costs, so be prepared to provide justification for any changes you would like to make to the estimate.'],
            ['question' => 'How do I select the right contractor for my project?', 'answer' => 'Choosing the right contractor for your project involves doing your research and gathering information from multiple sources. You can start by reading reviews from past clients, reviewing their ratings on Gonachi, interviewing multiple contractors to get a sense of their experience and approach to the project.'],
            ['question' => 'How long does it take to receive a contractor quotation?', 'answer' => 'The timeline for receiving a contractor quotation can vary depending on the scope of the project and the contractor\'s availability. It is important to communicate your timeline expectations with the contractor upfront to ensure that everyone is on the same page. See profile settings for Gonachi inbox alert option.'],

            //Add Home Buyers
            ['question' => 'What is the "add home buyers" functionality?', 'answer' => 'The "add home buyers" functionality is a feature on the Gonachi platform that allows users who are looking to purchase a home in a specific location to input information about their preferences. This includes both residential and comnmercial properties and also options for loading pictures and videos of desired property. This information will be available to all the realtors within this specific location and home buyers will have the ability to view realtors ratings from previous customers, connect with realtor of choice and buyers\'s information can then be used to match buyers with properties that fit their needs.'],
            ['question' => 'How do I access the "add home buyers" functionality on Gonachi?', 'answer' => 'To access the "add home buyers" functionality, log in to your Gonachi account and navigate to the menu bar, click on browse then home buyer and click on add home buyer. From there, begin inputting the basic details about your desired/dream property.'],
            ['question' => 'What information do I need to input when adding home buyers on Gonachi?', 'answer' => 'You will need to input basic information such as your user type, the desired location, type of property, time frame you are looking to buy, type of buy (commercial or residential), desired features, budget, any specific details you want including the ability to upload pictures and YouTube videos.'],
            ['question' => 'Can I add multiple home buyers to my Gonachi account?', 'answer' => 'Yes, you can add as many homes as you like to your Gonachi account.'],
            ['question' => 'How does the matching process work on Gonachi?', 'answer' => 'When you add a home buyer to your Gonachi account, your entry will be displayed to all the realtors that match your criteria. You can view their ratings and contact yur realtor of choice through Gonachi inbox.'],
            ['question' => 'Can I customize the matching criteria for my home buyers on Gonachi?', 'answer' => 'Yes, you can customize the matching criteria for your home buyers by adjusting your budget, location preferences, and desired features. This can help to refine the matching process.'],
            ['question' => 'Is the "add home buyers" functionality available to all users on Gonachi?', 'answer' => 'Yes, the "add home buyers" functionality is available to every user who have a Gonachi account. If you are a buyer you can still use the platform to search for properties and connect with agents.'],

            // Followers
            ['question' => 'What is the Followers functionality on Gonachi Real Estate social media platform?', 'answer' => 'The Followers functionality on Gonachi Real Estate social media platform allows other users to follow you and receive updates on your activities and posts. Because they follow you they become your "followers".'],
            ['question' => 'How can a user become my follower on Gonachi Real Estate social media platform?', 'answer' => 'A user can become your follower on Gonachi Real Estate social media platform, once you accept the user\'s network request, the user follows you hence "follower".'],
            ['question' => 'Can a user unfollow me on Gonachi Real Estate social media platform?', 'answer' => 'Yes, a user can unfollow you on Gonachi Real Estate social media platform when the user deletes you on their page.'],
            ['question' => 'How can I see who is following me on Gonachi Real Estate social media platform?', 'answer' => 'To see who follows you, on Gonachi Real Estate social media platform, simply visit the menu bar, click on dashboard then live feed, and on the left side of the page you click on followers tab and you will see the list of people who follow you (Followers).'],
            ['question' => 'Can I stop a user from following me on Gonachi Real Estate social media platform?', 'answer' => 'Yes, you can stop a user from following me on Gonachi Real Estate social media platform by deleting the user \'s request on your followers page.'],
            ['question' => 'Is there a limit on the number of followers on Gonachi Real Estate social media platform?', 'answer' => 'No there is no limit on the number of followers on Gonachi Real Estate social media.'],

            // Following
            ['question' => 'What is the Following functionality on Gonachi Real Estate social media platform?', 'answer' => 'The Following functionality on Gonachi Real Estate social media platform allows you to follow other users and receive updates on their activities and posts.'],
            ['question' => 'How can I follow someone on Gonachi Real Estate social media platform?', 'answer' => 'To follow someone on Gonachi Real Estate social media platform, simply visit the main menu bar then click on the dashboard, then live feed then click on requests on the left side of the page. Once you click on requests you can search the person you want to follow by entering the email address or full name. The person must be a Gonachi user to display and once displayed click on the person and hit search button and you can send a request to follow. Once the person accepts your request you now follow the person hence "following".'],
            ['question' => 'Can I unfollow someone on Gonachi Real Estate social media platform?', 'answer' => 'Yes, you can unfollow someone on Gonachi Real Estate social media platform. simply visit the menu bar, click on dashboard then live feed, and on the left side of the page you click on following tab and hit delete button.'],
            ['question' => 'How can I see who I am following on Gonachi Real Estate social media platform?', 'answer' => 'To see who you are following you on Gonachi Real Estate social media platform, simply visit the menu bar, click on dashboard then live feed, and on the left side of the page you click on following tab and you will see the list of people you are following.'],
            ['question' => 'Can a user prevent me from following on Gonachi Real Estate social media platform?', 'answer' => 'Yes, a user can stop you from following on Gonachi Real Estate social media platform by deleting your request on their followers page.'],
            ['question' => 'Is there a limit on the number of following on Gonachi Real Estate social media platform?', 'answer' => 'No you can increase your number of following on Gonachi Real Estate social media, there is no limit.'],

            // Network Requests
            ['question' => 'How can I make a network request on Gonachi Real Estate social media platform?', 'answer' => 'To make a network request on Gonachi Real Estate social media platform, go to the menu bad , click on dashboard, scroll to network request and click on it. You can send network request by either using the person\'s email adress or the full name then search and the system will display the user. The person you are sending a network request must be a Gonachi user for you to find the person.'],
            ['question' => 'How long does it take for someone to accept my network request on Gonachi Real Estate social media platform?', 'answer' => 'It varies based on the person you are requesting to connect with. Some may accept the request immediately, while others may take a few days, even weeks or more to respond. Some may decline the request and some may not respond.'],
            ['question' => 'Can I cancel a network request on Gonachi Real Estate social media platform?', 'answer' => 'Yes, you can cancel a network request on Gonachi Real Estate social media platform by going the menu ba,r click on dashboard then life feed then requests and you will see all your requests then click on the request you would like to cancel then click delete button.'],
            ['question' => 'How many network requests can I send on Gonachi Real Estate social media platform?', 'answer' => 'There is no set limit on the number of network requests you can send on Gonachi Real Estate social media platform. However, it\'s recommended to send requests only to people you have a genuine interest in connecting with and to personalize each request message.'],
            ['question' => 'Can I send a network request to someone I don\'t know on Gonachi Real Estate social media platform?', 'answer' => 'Yes, you can send a network request to someone you don\'t know on Gonachi Real Estate social media platform. However, it\'s important to personalize your message via Gonachi inbox and explain why you would like to connect with them.'],
            ['question' => 'How can I improve my chances of having my network request accepted on Gonachi Real Estate social media platform?', 'answer' => 'To improve your chances of having your network request accepted on Gonachi Real Estate social media platform, it\'s recommended to personalize your message, explain why you would like to connect, and highlight how you believe you can add value to each other\'s professional network. It\'s also important to have a complete profile with relevant information about your professional experience and skills.'],

            // Profile
            ['question' => 'What is Gonachi user profile page?', 'answer' => 'Gonachi user profile page is a page on Gonachi website that displays a user\'s profile information, including their username, user type, profile picture, bio, and other relevant details.'],
            ['question' => 'How do I access my Gonachi user profile page?', 'answer' => 'To access your Gonachi user profile page, log in to your account on the Gonachi website and go to the menu bar and click on profile.'],
            ['question' => 'Can I edit my profile information on my Gonachi user profile page?', 'answer' => 'Yes, you can edit your profile information on your Gonachi user profile page. Simply click on the "Edit " button on the top right corner of your profile page, follow the steps to make the necessary changes, and click "Submit" to update your profile information.'],
            ['question' => 'Can I change my password on my Gonachi user profile page?', 'answer' => 'Yes, you can change your password on your Gonachi user profile page. Go to your profile page, scroll down to user details and click "change". Enter your new password and follow the steps click "Submit" to update your password.'],
            ['question' => 'How can I change my profile picture on my Gonachi user profile page?', 'answer' => 'To change your profile picture on your Gonachi user profile page, click on the "pic " button, browse then upload a new picture from your computer or select one from your existing photos.'],
            ['question' => 'What other information Can I edit on my Gonachi profile page?', 'answer' => 'You can edit other information on Gonachi profile page, if you are a contractor you will be able to add or delete skills and edit contractor location settings this will determine the quotation request you will be able to receive within your specified location. if you are a real estate agent you will be able to edit Realtor home sellers?home buyers Settings. This will enable you to find home sellers and home buyers within your settings'],

            // Find Home Sellers
            ['question' => 'How can I find home sellers on Gonachi?', 'answer' => 'Gonachi offers several ways to find home sellers on its platform. One way is to use find home seller button and use the search function to type in your city. The find home seller browse is set to reflect the the options you chose in your profile under home seller and home buyer request settings. This implies that you will be able to search for home sellers in any city within the area you selected on your settings. Another option is through the "Browse advert " section and look for properties that have been listed by the owner. You can also browse real estate agents services who may be able to connect you with home sellers.'],
            ['question' => 'Can I contact home sellers directly through Gonachi?', 'answer' => 'Yes, you can use Gonachi to message home sellers directly through Gonachi inbox and if they have listed their contact information on their profile or property listing. You can also connect with home sellers through real estate agents who may have access to exclusive listings or off-market properties.'],
            ['question' => 'Are there any tips for finding home sellers on Gonachi?', 'answer' => 'To maximize your chances of finding home sellers on Gonachi, be sure to use specific search terms and filters to narrow down your results. You may also want to join relevant groups or forums where home sellers or real estate agents are active. Additionally, consider reaching out to your existing network on Gonachi to see if anyone knows of any home sellers who may be interested in working with you.'],
            ['question' => 'Is there a fee to use Gonachi to find home sellers?', 'answer' => 'Gonachi is free to use for both buyers and sellers but Real estate agents may also charge a commission fee for their services, which is typically a percentage of the sale price of the property. Gonachi does not determine or involve in these fees but only connects users.'],
            ['question' => 'How can I ensure that I find reputable home sellers on Gonachi?', 'answer' => 'Gonachi takes measures to verify the identities and credentials of its users, but it\'s still important to exercise caution and do your own research when working with home sellers or real estate agents. Be sure to read reviews and ratings from other users, and consider working with a licensed and experienced real estate professional to help guide you through the process.'],

            // Find Home Buyers
            ['question' => 'How can I find home buyers on Gonachi?', 'answer' => 'Gonachi offers several ways to find home buyers on its platform. One way is to use find home buyer button and use the search function and type in your city. The find home buyer browse is set to reflect the the options you chose in your profile under home buyer and home seller request settings. This implies that you will be able to search for home buyers in any city within the area you selected in your settings. Another option is through the "Browse advert " section and look for potential home buyers. You can also browse real estate agents services who may be able to connect you with home buyers.'],
            ['question' => 'Can I contact home buyers directly through Gonachi?', 'answer' => 'Yes, you can use Gonachi to message home buyers directly through Gonachi inbox. You can also connect with home buyers through real estate agents who may have access to potential home buyers.'],
            ['question' => 'Are there any tips for finding home buyers on Gonachi?', 'answer' => 'To maximize your chances of finding home buyers on Gonachi, be sure to use specific search terms and filters to narrow down your results. You may also want to join relevant groups or forums where home buyers or real estate agents are active. Additionally, consider reaching out to your existing network on Gonachi to see if anyone knows of any home buyers who may be interested in working with you.'],
            ['question' => 'Is there a fee to use Gonachi to find home buyers?', 'answer' => 'Gonachi is free to use for both buyers and sellers but Real estate agents may also charge a commission fee for their services, which is typically a percentage of the sale price of the property. Gonachi does not determine or involve in these fees but only connects users.'],
            ['question' => 'How can I ensure that I find reputable home buyers on Gonachi?', 'answer' => 'Gonachi takes measures to verify the identities and credentials of its users, but it\'s still important to exercise caution and do your own research when working with home buyers or real estate agents. Be sure to read reviews and ratings from other users, and consider working with a licensed and experienced real estate professional to help guide you through the process.'],

            // Add Home Sellers
            ['question' => 'What is the "add home sellers" functionality?', 'answer' => 'The "add home sellers" functionality is a feature on the Gonachi platform that allows user who is looking to sell a home in a specific location to input information about the property. This includes both residential and comnmercial properties and also options for loading pictures and videos of the property. This information will be available to all the realtors within this specific location and home sellers will have the ability to view realtors ratings from previous customers, connect with realtor of choice and seller\'s information can then be used to match sellers with prospective buyers.'],
            ['question' => 'How do I access the "add home seller" functionality on Gonachi?', 'answer' => 'To access the "add home seller" functionality, log in to your Gonachi account and navigate to the menu bar, click on browse then home seller and click on add home seller. From there, begin inputting the basic details about your property.'],
            ['question' => 'What information do I need to input when adding home seller on Gonachi?', 'answer' => 'You will need to input basic information such as your user type, the location of the house, type of property, time frame you are looking to sell, type of sell (commercial or residential), home features, offer range or expected sale price, closing dates any specific details you want including the ability to upload pictures and youtube videos.'],
            ['question' => 'Can I add multiple homes to my Gonachi account?', 'answer' => 'Yes, you can add as many homes as you like to your Gonachi account.'],
            ['question' => 'How does the matching process work on Gonachi?', 'answer' => 'When you add a home seller to your Gonachi account, your enry will be displayed to all the realtors that match your criteria. You can view their ratings and contact yur realtor of choice through Gonachi inbox.'],
            ['question' => 'Can I customize the matching criteria for my home seller on Gonachi?', 'answer' => 'Yes, you can customize the matching criteria for your home seller by adjusting your expected sales price, location preferences, and expected closing dates. This can help to refine the matching process.'],
            ['question' => 'Is the "add home buyers" functionality available to all users on Gonachi?', 'answer' => 'Yes, the "add home seller" functionality is available to every user who have a Gonachi account. If you are a seller you can still use the platform to search for properties and connect with agents.'],

            // Find Recommended Users
            ['question' => 'How can I find recommended users on Gonachi Real Estate Platform?', 'answer' => 'To find recommended users on Gonachi Real Estate Platform, follow these steps: Log in to your account on Gonachi Real Estate Platform. Click on the browse buton in the top menu bar, go to recommend and click on find recommended users. Follow the steps: you can find recommended using two criteria on Gonachi: 1. Location and user type specific and 2. Individual. Location and user type specific: By entering the country, region/state, city and user type then click on find. These option will show you all the users recommended on Gonachi within these search criteria. Individual: By entering user\'s email address or full name, the system displays the user then click on the user and then find user. This option will display all the users who recommended the individual and also display other users recommended by the individual.'],
            ['question' => 'What kind of users can I find on Gonachi Real Estate Platform?', 'answer' => 'Gonachi Real Estate Platform has a wide range of users, including real estate agents, property managers,mortgage agents, landlords, contractots, tenants, and property owners. You can use the platform to find users who can help you buy, sell, or rent a property, as well as those who can provide property management services.'],
            ['question' => 'Can I contact recommended users directly on Gonachi Real Estate Platform?', 'answer' => 'Yes, you can contact recommended users directly on Gonachi Real Estate Platform. Each user can be contacted when you place the mouse over the user\'s profile picture and click, it will display the user\'s profile and it allows you to send a message to the user.'],
            ['question' => 'How are recommended users selected on Gonachi Real Estate Platform?', 'answer' => 'Gonachi does not have any influence on how users are recommended , all recommendations are based on individual user experiences. Gonachi ensourages user to provide honest recommendation and to the best of user\'s ability.'],
            ['question' => 'Is it free to find recommended users on Gonachi Real Estate Platform?', 'answer' => 'Yes, it is free to find recommended users on Gonachi Real Estate Platform. The platform does not charge any fees for searching for or contacting users.'],

            // Recommend Users
            ['question' => 'What is the "Recommend a User to Other Users" functionality on Gonachi real estate platform?', 'answer' => 'The "Recommend a User to Other Users" functionality on Gonachi real estate platform is a feature that allows users to suggest other users to their connections or followers on the platform.'],
            ['question' => 'How can I use the "Recommend a User to Other Users" functionality on Gonachi real estate platform?', 'answer' => 'To use this feature, you need to be a registered user of the platform. Once you are logged in, you can visit the menu bar, click on browse, recommend and then recommend user button. You will need to provide the email address or full name of the user to display the user then find user. You can recommend user based on location and user type, can recommend to a specific user or users in same category e.g. recommending a tenant to landlors in a specic location or recommending a contractor to landlors or realtors in a specific location.'],
            ['question' => 'What are the benefits of using the "Recommend a User to Other Users" functionality on Gonachi real estate platform?', 'answer' => 'There are several benefits of using this functionality. Firstly, it helps users to expand their network and connect with more people who share similar interests or goals. Secondly, it allows users to show appreciation for the work or contribution of other users on the platform. Finally, it can help users to build their reputation and increase their visibility on the platform.'],
            ['question' => 'Is there a limit to the number of users I can recommend on Gonachi real estate platform?', 'answer' => 'There is no specific limit to the number of users you can recommend on Gonachi real estate platform. However, it is recommended that you only recommend users who you know and trust, and who you believe will add value to the network.'],
            ['question' => 'Will the user I recommend receive a notification?', 'answer' => 'Yes, the user you recommend will receive a notification in their Gonachi inbox that you have recommended them. They will also be able to see the recommendation on their page.'],
            ['question' => 'Can I remove a recommendation after I have made it?', 'answer' => 'No, once you submit a recommendation on Gonachi Real Estate Platform, you cannot edit or delete it.'],
            ['question' => 'What should I include in my recommendation?', 'answer' => 'When making a recommendation, it is important to provide a brief description of why you are recommending the user. This could include their expertise, their contribution to the community, your positive experiences dealing with the user, or their helpfulness in responding to your queries. It is also recommended that you be honest and specific in your recommendation.'],

            // Browse Ratings
            ['question' => 'How do I browse user ratings on Gonachi?', 'answer' => 'To browse user ratings on Gonachi, simply visit the website and use menu bar click on browse, go to ratings then browse ratings. There are two criteria for browse user ratings on Gonachi: 1. Location and user type specific and 2. Individual. Location and user type specific: By entering the country , region/state, city and user type then click on find. These option will show you all the users rated on Gonachi within these search criteria. Individual: By entering user\'s email address or full name then find user. This option will display the individual user, click on the user and you will see all ratings on Gonachi.'],
            ['question' => 'How reliable are the user ratings on Gonachi?', 'answer' => 'The reliability of user ratings on Gonachi can vary, as they are based on the opinions and experiences of individual users/raters. However, Gonachi encourage users to be honest and rate based on their genuine experences.'],
            ['question' => 'Are there any rules or guidelines for leaving ratings and reviews on Gonachi?', 'answer' => 'Yes, Gonachi has a set of community guidelines that users are expected to follow when leaving ratings and reviews. Some of the key guidelines include being honest and transparent in your feedback, avoiding personal attacks or offensive language, and not posting spam or promotional content. Gonachi reserves the right to remove any ratings or reviews that violate these guidelines.'],
            ['question' => 'Can I trust the average rating on Gonachi?', 'answer' => 'The average rating on Gonachi can be a helpful indicator of the overall quality of a product or service, or experience, but it is important to keep in mind that it is based on a relatively small sample size of user ratings. Additionally, people\'s experiences and opinions can vary widely, so it is always a good idea to read through a variety of reviews to get a more complete picture of what to expect.'],

            // Rate Users
            ['question' => 'What does it mean to rate a user on Gonachi?', 'answer' => 'Rating a user on Gonachi means giving them a score or a rating based on your experience with them. This could include factors such as their behavior, communication skills, or overall interaction with you.'],
            ['question' => 'How do I rate a user on Gonachi?', 'answer' => 'To rate a user on Gonachi, you can go to the menu bar and click on browse and then rate user button. From there, you can search the user by the email address or the user\'s full name. You must know the user\'s email address or name to be able to find the user and rate. You must choose in which location you want to rate the user, You must choose a category in which you are rating user so other can find your rating within same category e.g. rating as a contractor, real estate agent, mortgage broker, tenant, landlord and property manager. Be honest and specific in your rating as it will help other buyers make informed decisions.'],
            ['question' => 'Can I rate someone who is not a Gonachi user?', 'answer' => 'No, you can only rate someone who is a registered user of Gonachi who you have interacted with in one or different capacities.'],
            ['question' => 'Can I rate a user anonymously on Gonachi?', 'answer' => 'No at this point Gonachi has no option for anonymous rating. However, keep in mind that anonymous ratings may not be as credible or helpful as ratings that are associated with a user\'s name.'],
            ['question' => 'What happens after I rate a user on Gonachi?', 'answer' => 'After you rate a user on Gonachi, your rating and feedback will be added to their overall rating score. Other users will be able to see your rating and feedback when they visit that user\'s profile.'],
            ['question' => 'Can I change my rating for a user on Gonachi?', 'answer' => 'Yes, you can change your rating for a user on Gonachi at any time. Simply go to view your ratings, click on the rating and "Edit Rating" button.'],
            ['question' => 'What should I consider when rating a user on Gonachi?', 'answer' => 'When rating a user on Gonachi, you should consider factors such as their communication skills, reliability, trustworthiness, and overall behavior. Be honest and constructive in your feedback, and provide specific examples if possible.'],
            ['question' => 'Can Gonachi remove a rating if it\'s inappropriate or inaccurate?', 'answer' => 'Gonachi does not control or determine ratings of users but reserves the right to remove ratings that are deemed inappropriate or inaccurate. If you believe that a rating is unfair or inaccurate, you can contact Gonachi support to request a review.'],

            // Browse Adverts
            ['question' => 'How do I browse an AD on Gonachi?', 'answer' => 'To browse an AD on Gonachi, follow these steps: Go to the Gonachi homepage Browse-browse advert. Use the search bars to select your country, region, city (optional), advert category and advert category types. to find the item or service you are looking for. Once you find the item or service you are interested in, click on the AD to view the details. You can then view the images, read the description, and check the price of the item or service. If you are interested in buying the item or service, you can contact the seller directly through the messaging feature on Gonachi.'],
            ['question' => 'How do I contact the seller?', 'answer' => 'To contact the seller, use the messaging feature on Gonachi. Click on the "Contact seller" button on the AD page, and send them a message with your questions or offer.'],
            ['question' => 'Is it safe to buy from Gonachi?', 'answer' => 'Gonachi takes safety and security very seriously. The platform uses advanced security measures to protect your personal information and transactions. However, it\'s always a good idea to do your own research on the seller and the item or service before making a purchase.'],
            ['question' => 'How do I pay for my purchase on Gonachi?', 'answer' => 'Gonachi only connects sellers and buyers.'],
            ['question' => 'How do I leave feedback for the seller?', 'answer' => 'You will have the opportunity to leave feedback for the seller. Simply go to Gonachi rating system or Recommendation system for this purpose. Be honest and specific in your rating or recommendation as it will help other buyers make informed decisions.'],

            // View My Adverts
            ['question' => 'Can I view my own ads on the platform where I\'m advertising?', 'answer' => 'Yes, you can view your own ads on Gonachi, view number of visits, and edit or delete own adverts.'],
            ['question' => 'Why would I want to view my own ads?', 'answer' => 'There are a few reasons why you might want to view your own ads. For example, you may want to check that your ad is displaying correctly, ensure that the correct targeting settings are in place, or verify that the ad is being displayed in the right location.'],
            ['question' => 'How do I view my own ads?', 'answer' => 'The process for viewing your own ads will depend on the specific platform where you are advertising. Generally, you can search for your own ad by entering relevant keywords or phrases into the search bar on the platform. You can also navigate to the specific ad placement where your ad is supposed to appear and refresh the page to see if the ad is displaying.'],
            ['question' => 'Are there any restrictions or guidelines for viewing my own ads?', 'answer' => 'No because clicking on you r own ads cannot inflate clicks or add to metrics for number of viewers to the ad.'],
            ['question' => 'Can viewing my own ads have any impact on my ad performance?', 'answer' => 'In general, viewing your own ads should not have a significant impact on ad performance.'],

            // Post Ads on Gonachi
            ['question' => 'Is there a fee to post an ad on Gonachi?', 'answer' => 'No, there is no fee to post an ad on Gonachi.'],
            ['question' => 'Are there any restrictions on what I can sell on Gonachi?', 'answer' => 'Yes, there are some restrictions on what you can sell on Gonachi. For example, you cannot sell illegal or stolen goods, counterfeit items, or items that are prohibited by law.'],
            ['question' => 'How long does my ad stay on Gonachi?', 'answer' => 'The duration of your ad on Gonachi depends on the package you choose while posting the ad.'],
            ['question' => 'Can I edit or delete my ad after it is posted?', 'answer' => 'Yes, you can edit or delete your ad after it is posted by logging into your account and making the necessary changes.'],
            ['question' => 'How do I contact someone who has posted an ad on Gonachi?', 'answer' => 'You can contact the seller directly by using the contact details provided in the ad and through Gonachi inbox.'],
            ['question' => 'Is it safe to buy and sell on Gonachi?', 'answer' => 'Gonachi strives to provide a safe and secure marketplace for buyers and sellers. However, it is important to take precautions when buying and selling online, such as meeting in a public place when completing a transaction, using secure payment methods, and verifying the identity of the other party.'],
            ['question' => 'How can I promote my ad on Gonachi?', 'answer' => 'Gonachi offers various paid ad promotion packages, and you can also promote your ad on your social media accounts and other online platforms.'],
            ['question' => 'What should I do if I suspect fraud or scam on Gonachi?', 'answer' => 'If you suspect fraud or scam on Gonachi, please report the ad and the user to the Gonachi team immediately.'],

            // Social Feed
            ['question' => 'What is Gonachi Real Estate social feed and Social Media Platform?', 'answer' => 'Gonachi Real Estate social feed and Social Media Platform is an online platform for real estate professionals and enthusiasts that allows them to connect, share insights, and stay updated on the latest trends in the industry. The social feed allows user to invite other users as your friends through network request, see network suggestions, follow individuals (following) and or allow other users to follow you (followers).'],
            ['question' => 'Who can use Gonachi Real Estate social feed and Social Media Platform?', 'answer' => 'Anyone who is a Gonachi user can use the platform, including real estate agents, brokers, investors, property managers, tenants, contractors and other industry professionals.'],
            ['question' => 'What features does Gonachi Real Estate social feed and Social Media Platform offer?', 'answer' => 'The platform offers a range of features, including a news feed that displays the latest real estate news, updates, and insights, as well as a social media component that allows users to connect with other professionals and share their own content. Users can also create and join groups, participate in discussions, and access a directory of industry professionals. On social feed, users can post videos using YouTube web links, post comments, pictures, files while anyone on user’s network can comments and like on your page. Also, social feed allows user to view the number of network request accepted by the user(following).'],
            ['question' => 'Is Gonachi Real Estate social feed and Social Media Platform free to use?', 'answer' => 'Yes, the platform is free to use for all users.'],
            ['question' => 'How can I sign up for Gonachi Real Estate social feed and Social Media Platform?', 'answer' => 'Users can sign up for the platform by visiting the Gonachi website and creating a profile.'],
            ['question' => 'Is Gonachi Real Estate social feed and Social Media Platform secure?', 'answer' => 'Yes, the platform uses encryption and other security measures to protect user data and information.'],
            ['question' => 'Can I advertise my real estate services on Gonachi Real Estate social feed and Social Media Platform?', 'answer' => 'Yes, users can advertise their real estate services on the platform by creating a business page or joining relevant groups.'],
            ['question' => 'Can I access Gonachi Real Estate social feed and Social Media Platform on my mobile device?', 'answer' => 'Yes, the platform is mobile-friendly'],
            ['question' => 'How can I report inappropriate content or behavior on Gonachi Real Estate social feed and Social Media Platform?', 'answer' => 'Users can report inappropriate content or behavior by contacting the platform\'s support team.'],

            // Tenant Validation
            ['question' => 'How do I view tenant validation requests on Gonachi?', 'answer' => 'To view tenant validation requests on Gonachi, you need to log in to your account, navigate to the menu bar, click on browse then "Tenants" tab, and select "Validation Requests." This will show you a list of all current tenant validation requests.'],
            ['question' => 'What information will be displayed in a tenant validation request on Gonachi?', 'answer' => 'A tenant validation request on Gonachi will display the tenant\'s being validated, the landlord requesting the validation, the landlord who submitted the documents for validation, the documents requested, and the documents provided/ uploaded.'],
            ['question' => 'What types of validation requests can landlords submit on Gonachi?', 'answer' => 'landlords can request various types of validation documents on Gonachi, such as proof E-transfer by tenants, lease agreement showing both landlord and tenant’s name, mails(s) tenant received showing property address of the previous landlord, copy or copies of tenant’s postdated cheques and any other supporting documents by the landlord to validate tenant.'],
            ['question' => 'How do I approve or reject a tenant validation request on Gonachi?', 'answer' => 'To approve or reject a tenant validation request on Gonachi, simply click on the request and review the information provided. You can then choose to approve or reject the request and provide a reason for your decision.'],
            ['question' => 'Can I communicate with tenants regarding their validation requests on Gonachi?', 'answer' => 'Yes, Gonachi allows landlords and property managers to communicate with tenants regarding their validation requests. You can send messages directly through the platform and keep all communication in one place.'],
            ['question' => 'Is there a fee for using Gonachi\'s tenant validation request feature?', 'answer' => 'Gonachi is free for now but in the future Gonachi may offer different pricing plans, including a free plan that includes basic features such as tenant validation requests. However, more advanced features and larger numbers of properties and tenants may require a paid plan.'],

            // Request Tenant Validation
            ['question' => 'What is tenant validation request on Gonachi?', 'answer' => 'Tenant validation request on Gonachi is a process where landlords or property managers validate a potential tenant by requesting some documents from the tenant’s previous landlord. The essence is to limit the chances of tenants using their friend/s or family member/s when the potential landlord is doing a previous landlord preference check.'],
            ['question' => 'Why do landlords or property managers request tenant validation on Gonachi?', 'answer' => 'Landlords or property managers request tenant validation on Gonachi to minimize the risk of renting their properties to unreliable or fraudulent tenants. The process provides them with accurate information about the tenant\'s background and helps them make informed decisions about renting their properties.'],
            ['question' => 'How does tenant validation work on Gonachi?', 'answer' => 'To request tenant validation on Gonachi, landlords or property managers, tenants and previous landlord/s need to be a Gonachi users. They can then go to the menu bar click on browse, then request tenant validation. Tenant\'s previous landlord will validate relationship with tenant by providing few documents requested by the potential landlord to facilitate the previous landlord preference checks.'],
            ['question' => 'Is tenant validation on Gonachi secure?', 'answer' => 'Yes, tenant validation on Gonachi is secure. Gonachi uses industry-standard security protocols to protect the personal information of both the landlord and tenant. All data transmitted between the platform and the user is encrypted and stored in a secure database.'],
            ['question' => 'How long does tenant validation on Gonachi take?', 'answer' => 'The tenant validation process on Gonachi may vary depending on the complexity of the verification and the availability of the previous landlord to provide the required information.'],
            ['question' => 'What happens after the tenant validation process on Gonachi is completed?', 'answer' => 'After the tenant validation process on Gonachi is completed, the landlord or property manager will review the documents submitted by previous landlord. Based on the documents, the landlord or property manager can make an informed decision about renting their property to the tenant. If the tenant passes the verification, the landlord or property manager can proceed with the rental process. This process is not exclusive of other verifications required to be completed by the landlord or property manager'],
            ['question' => 'Is there a fee for tenant validation on Gonachi?', 'answer' => 'No, there is no fee for tenant validation on Gonachi, our services are free.'],

            // Mentors
            ['question' => 'How can I view my mentors on Gonachi?', 'answer' => 'To view your mentors on Gonachi, you need to go to browse on the menu bar click on mentors and then navigate to the "My Mentors" section. There, you can see a list of all the mentors you have been matched with.'],
            ['question' => 'Can I have multiple mentors on Gonachi?', 'answer' => 'Yes, you can have multiple mentors on Gonachi. The platform allows you to connect with as many mentors as you like in different fields or areas of interest.'],
            ['question' => 'How are mentors matched with mentees on Gonachi?', 'answer' => 'Gonachi uses a sophisticated matching algorithm that takes into account factors such as your career goals, industry, and professional experience to match you with mentors who have relevant expertise and experience.'],
            ['question' => 'Can I communicate with my mentors on Gonachi?', 'answer' => 'Yes, Gonachi provides a messaging feature that allows you to communicate with your mentors. You can send messages and share files with your mentors through Gonachi life feed or Gonachi groups.'],
            ['question' => 'How often should I communicate with my mentors on Gonachi?', 'answer' => 'The frequency of communication with your mentors on Gonachi is entirely up to you and your mentor. Some mentees may prefer to communicate with their mentors on a regular basis, while others may only need occasional check-ins.'],
            ['question' => 'How long does a mentorship relationship typically last on Gonachi?', 'answer' => 'The duration of a mentorship relationship on Gonachi can vary depending on the mentee\'s goals and the mentor\'s availability.'],
            ['question' => 'Can I change my mentor on Gonachi?', 'answer' => 'Yes, Gonachi allows you to request a new mentor at any time if you feel that your current mentor is not a good match or if your goals have changed.'],
            ['question' => 'Is Gonachi free to use?', 'answer' => 'Gonachi is free and connects you with mentors and access basic features'],

            // Request a Mentor
            ['question' => 'What is request a mentor?', 'answer' => 'Gonachi is an online platform that connects individuals who are seeking mentorship with experienced professionals who are willing to provide guidance and support.'],
            ['question' => 'How do I request a mentor on Gonachi?', 'answer' => 'To request a mentor on Gonachi, you need to go to the menu bar, click on browse then request a mentor by filling out a mentorship request form. In the form, you will be asked to provide information about your user type, location, your goals and areas where you would like guidance.'],
            ['question' => 'Is there a fee for requesting a mentor on Gonachi?', 'answer' => 'Gonachi does not charge a fee for requesting a mentor.'],
            ['question' => 'Who can request a mentor on Gonachi?', 'answer' => 'Anyone who is a Gonachi user and seeking guidance and support in their personal or professional life can request a mentor on Gonachi.'],
            ['question' => 'What kind of mentors are available on Gonachi?', 'answer' => 'Gonachi has a diverse pool of mentors with experience in various fields, including landlords, contractors, real estate agents, mortgage brokers and others.'],
            ['question' => 'How long does it take to get matched with a mentor?', 'answer' => 'The matching process varies depending on the availability of mentors and the specific criteria you have requested. Gonachi does not have control on how long it takes to connect to a mentor.'],
            ['question' => 'What is expected of me as a mentee?', 'answer' => 'As a mentee, you are expected to be committed to the mentorship process, set goals, and actively seek guidance from your mentor. You should also be respectful of your mentor\'s time and expertise.'],
            ['question' => 'Can I switch mentors if I am not satisfied with my match?', 'answer' => 'Yes, you can switch a mentor if you feel that the match is not working out. You can communicate with your mentor in a professional manner about your intent and you can go through the process on Gonachi, note that Gonachi only connects mentors and mentees.'],
            ['question' => 'How long does the mentorship relationship last?', 'answer' => 'The length of the mentorship relationship is determined by the mentor and mentee.'],
            ['question' => 'What are the benefits of having a mentor?', 'answer' => 'Having a mentor can provide you with valuable guidance, support, and insight into your personal or professional development. Mentors can help you set goals, develop skills, and provide feedback on your progress. They can also connect you with valuable resources and networks in your field.'],

            // Become a Mentor on Gonachi
            ['question' => 'What is Gonachi Mentor?', 'answer' => 'Gonachi is an online platform that connects mentors with mentees for various subjects and skills.'],
            ['question' => 'How can I become a mentor on Gonachi?', 'answer' => 'To become a mentor on Gonachi, go to the menu bar click on browse, mentor and become a mentor. You will make yourself available for Gonachi users looking for a mentor in your specific field/location. Create a profile highlighting your expertise in the subject or skill you wish to mentor others on.'],
            ['question' => 'What are the requirements to become a mentor on Gonachi?', 'answer' => 'To become a mentor on Gonachi, you must have expertise in the subject or skill you wish to mentor others on. You must also possess good communication and interpersonal skills to effectively teach and guide your mentees. Additionally, you should have a strong desire to help others and be able to commit to a regular mentoring schedule.'],
            ['question' => 'What kind of subjects and skills can I mentor on Gonachi?', 'answer' => 'Gonachi offers a wide range of subjects and skills that you can mentor on. These include but are not limited to mentoring new landlors who are interested in renting or tenants who are looking towards buying a new home, contractors interested in learning new skills/trade, users interested in becoming real estate agents or mortgage brokers.'],
            ['question' => 'How much can I earn as a mentor on Gonachi?', 'answer' => 'Gonachi only connects mentors and mentees.'],
            ['question' => 'What are some tips for being a successful mentor on Gonachi?', 'answer' => 'Some tips for being a successful mentor on Gonachi include being patient and empathetic with your mentees, setting clear goals and expectations, providing constructive feedback, and maintaining a professional demeanor. Additionally, it\'s important to stay up-to-date with the latest developments in your field and continuously improve your teaching skills.'],

            // Request Contractor Quotation
            ['question' => 'Why do I need a contractor quotation?', 'answer' => 'A contractor quotation provides you with an estimate of the costs associated with a project, which allows you to make an informed decision about whether to move forward with the project or not. It also allows you to compare prices between different contractors to ensure that you are getting the best value for your money.'],
            ['question' => 'How do I request a contractor quotation?', 'answer' => 'To request a contractor quotation, go to the menu bar, click on browse, quotation and request for quotation. You will need to provide details about the project, such as the scope of work, timelines, photos, videos and any other relevant information to ensure that the contractor can provide an accurate estimate.'],
            ['question' => 'What should be included in a contractor quotation?', 'answer' => 'A contractor quotation should include details about the scope of work, the estimated timeline for completion, the materials required, and any other costs associated with the project, such as permits or fees.'],
            ['question' => 'Can I negotiate the cost of the contractor quotation?', 'answer' => 'Yes, in most cases, you can negotiate the cost of the contractor quotation. However, it is important to keep in mind that the contractor has likely based their estimate on their costs, so be prepared to provide justification for any changes you would like to make to the estimate.'],
        ];

        foreach ($defaultFaqs as $index => $faq) {
            Faq::create([
                'question'      => $faq['question'],
                'answer'        => $faq['answer'],
                'status_id'     => Faq::STATUS_ACTIVE,
                'display_order' => $index + 1,
                'orig_user_id'  => 1,
            ]);
        }

        $messages[] = "seeded " . count($defaultFaqs) . " Gonachi faqs with active status";
    } catch (\Throwable $e) {
        $messages[] = "Error resetting " . ($tableName ?? 'faqs') . " table: " . $e->getMessage();
    }

    return $messages;
}
