// /resources/js/app.js

// === Global CSS ===
import '../css/app.css';

// 1. IMPORT Alpine and the Store FIRST
import Alpine from 'alpinejs';
import { initSidebarStore } from './utils/sidebar-state.js';

// 2. Initialize the listener immediately
initSidebarStore();

// 3. Set global and start
window.Alpine = Alpine;
Alpine.start();

// === Polyfills ===
import './utils/polyfills.js';

// === Global Modules ===
//import { initTooltips } from './ui/tooltip.js';
import { setupScrollToTop } from './ui/scroll-to-top.js';
import { setupSpinner } from './ui/spinner.js';
import { bindPartialLinks } from './utils/spa-router.js';
import { initDarkMode } from './utils/dark-mode.js';
import { LoginModal } from './modals/login-modal.js';
import { LogoutModal } from './modals/logout-modal.js';
import { ResetModal } from './modals/reset-modal.js';
import { initSidebarToggle } from './utils/sidebar-utils.js';
import { initHeaderIcons } from './ui/header-icons.js';
import { initFooterLinks } from './ui/footer-links.js';
import { cleanupModals } from './utils/modal-cleanup.js';

// === Page Manifest ===
let PAGE_MANIFEST = [];

// === Global Modal Initializer ===
let loginModal, logoutModal, resetModal;

function initGlobalModals() {
  loginModal = new LoginModal('a[data-login-button]');
  logoutModal = new LogoutModal('a[data-logout-button]');
  resetModal = new ResetModal('[data-reset-button]');
}

/**
 * Load the page-manifest.json generated by Vite
 */
async function loadPageManifest() {
  try {
    const res = await fetch(`${window.APP_CONFIG.assetBase}assets/js/page-manifest.json`);
    PAGE_MANIFEST = res.ok ? await res.json() : [];
  } catch (err) {
    console.error('Failed to load page-manifest.json:', err);
    PAGE_MANIFEST = [];
  }
}

/**
 * Dynamically import a page script if it exists.
 * Sub-folder aware: Strips the app's base path before matching segments.
 */
async function initPageScript(urlPathname) {
    // 1. Get the base path string (e.g., "/catscript-apps" or "https://site.com/catscript-apps")
    let baseUrl = window.APP_CONFIG.baseUrl || '';
    
    // 2. Extract just the pathname if it's a full URL, otherwise use as is
    if (baseUrl.includes('://')) {
        try {
            baseUrl = new URL(baseUrl).pathname;
        } catch (e) {
            baseUrl = baseUrl.replace(/^https?:\/\/[^\/]+/, ''); 
        }
    }
    
    // Clean trailing slashes so "/catscript-apps/" becomes "/catscript-apps"
    const cleanBase = baseUrl.replace(/\/$/, "");
    
    // 3. Subtract the base from the current path
    let internalPath = urlPathname;
    if (cleanBase && urlPathname.startsWith(cleanBase)) {
        internalPath = urlPathname.substring(cleanBase.length);
    }

    // 4. Clean segments
    const segments = internalPath.split('/').filter(Boolean);
    
    // 5. Handle Home Page (Root of the app)
    if (segments.length === 0) {
        await loadModule('home-page');
        return;
    }

    // 6. The Search: Check segments (reversed to find the most specific page)
    let moduleLoaded = false;
    for (const segment of [...segments].reverse()) {
        const scriptKey = `${segment}-page`;
        if (PAGE_MANIFEST.includes(scriptKey)) {
            await loadModule(scriptKey);
            moduleLoaded = true;
            break; 
        }
    }

    // 7. Fallback
    if (!moduleLoaded && segments.length === 0) {
        await loadModule('home-page');
    }
}

/**
 * Helper: Reconstructs the Vite path and executes the module init
 */
async function loadModule(scriptKey) {
    // Extra safety: Don't try to load if manifest isn't an array or doesn't have the key
    if (!Array.isArray(PAGE_MANIFEST) || !PAGE_MANIFEST.includes(scriptKey)) return;

    const scriptPath = `${window.APP_CONFIG.assetBase}assets/js/${scriptKey}.min.js`;
    
    try {
        const module = await import(/* @vite-ignore */ scriptPath);
        if (module.init) {
            module.init();
            //console.log(`✅ Feature initialized: ${scriptKey}`);
        }
    } catch (err) {
        // Log error but keep the rest of app.js alive
        console.warn(`⚠️ Could not load feature module: ${scriptKey}`, err);
    }
}

// === Define protected paths ===
// Use the paths passed from PHP
const PROTECTED_PATHS = window.APP_CONFIG.protectedPaths || [];

/**
 * Checks if page is protected and user is logged in
 * Returns true if page script should be loaded
 */
function shouldLoadPageScript(path) {
  if (PROTECTED_PATHS.includes(path) && !window.sessionUserId) {
    console.log(`ℹ️ Protected page "${path}" detected, user not logged in — skipping page script.`);
    return false;
  }
  return true;
}

// === DOMContentLoaded ===
document.addEventListener('DOMContentLoaded', async () => {
  // Initialize global UI
  setupSpinner();
  setupScrollToTop();
  bindPartialLinks();
  initDarkMode();
  initSidebarToggle();
  initFooterLinks();

  // Initialize modals
  initGlobalModals();

  // PRECISION TRIGGER: Check for login request
  const urlParams = new URLSearchParams(window.location.search);
  if (urlParams.has('login')) {
      // Give the UI a tiny heartbeat to settle, then pop the modal
      setTimeout(() => {
          // Check if LoginModal class has a show/open method
          // Usually, you can trigger the click on the data-login-button 
          // or call the method directly if you stored the instance
          const loginBtn = document.querySelector('a[data-login-button]');
          if (loginBtn) loginBtn.click();
      }, 500);
      
      // Clean the URL so refreshing doesn't keep popping the modal
      window.history.replaceState({}, document.title, window.location.pathname);
  }
  
  const sessionUserId = window.sessionUserId;
  if (sessionUserId){
    initHeaderIcons();
  }

  // 🔑 Load manifest first
  await loadPageManifest();

  // 🔑 PRECISION FIX: Strip query strings and hashes for the router
  const cleanPath = window.location.pathname.replace(/\/$/, '');

  // 🔒 Only load page-specific script if allowed
  if (shouldLoadPageScript(window.location.pathname)) {
    await initPageScript(window.location.pathname);
  }
});

// === SPA partial-load event ===
// Triggered by spa-router.js after partial page replacement.
// Ensures per-page scripts and modals reinitialize correctly
// once the new DOM content is fully rendered.
document.body.addEventListener('partial-load', (e) => {
  const url = e.detail?.url || '';

  try {
    const parsedUrl = new URL(url, window.location.origin);

    // 🔑 PRECISION FIX: Use parsedUrl.pathname to ignore ?token=...
    const cleanPath = parsedUrl.pathname.replace(/\/$/, '');

    // 🔒 Skip page script initialization for protected pages if not logged in
    if (!shouldLoadPageScript(parsedUrl.pathname)) return;

    // 🕒 Wait briefly to ensure #main-content's new HTML is fully parsed & attached
    // This prevents "missing DOM elements" issues in modules like messages-page.js
    setTimeout(async () => {
      try {
        cleanupModals();            // 🧹 Remove old modals & MutationObservers
        await initPageScript(parsedUrl.pathname); // 🚀 Load & init the new page script
        initGlobalModals();         // 🔁 Rebind login/logout/reset modals
      } catch (err) {
        console.error('Failed to initialize page script after partial load:', err);
      }
    }, 25); // ← Small delay ensures DOM is ready (25ms is enough)

  } catch (err) {
    console.error('Failed to parse SPA partial URL for page script:', err);
  }
});
