<?php
// /resources/views/components/quotes/view-quote-modal.php
?>

<style>
    /* Custom Stylish Scrollbar for the Modal Content */
    #view-quote-modal-content::-webkit-scrollbar {
        width: 6px;
    }

    #view-quote-modal-content::-webkit-scrollbar-track {
        background: transparent;
        margin: 10px;
    }

    #view-quote-modal-content::-webkit-scrollbar-thumb {
        background: #cbd5e1;
        border-radius: 10px;
        border: 2px solid transparent;
    }

    .dark #view-quote-modal-content::-webkit-scrollbar-thumb {
        background: #334155;
    }

    #view-quote-modal-content::-webkit-scrollbar-thumb:hover {
        background: #dc2626; /* Red 600 (Primary) */
    }
</style>

<div id="view-quote-modal" class="fixed inset-0 z-50 hidden">
    <div id="close-view-quote-modal-overlay" class="absolute inset-0 bg-gray-950/60 backdrop-blur-sm transition-opacity"></div>

    <div class="fixed inset-0 z-50 flex items-center justify-center p-4">
        <div class="bg-white dark:bg-gray-900 w-full max-w-5xl rounded-[2.5rem] shadow-2xl border border-gray-200 dark:border-gray-800 overflow-hidden transform transition-all animate-in fade-in zoom-in duration-200">

            <div class="px-8 py-6 border-b border-gray-100 dark:border-gray-800 flex items-center justify-between bg-gray-50/50 dark:bg-gray-800/50">
                <div class="flex items-center space-x-5 overflow-hidden">
                    <div id="view-quote-icon-container" class="h-14 w-14 flex-shrink-0 rounded-2xl bg-red-600 flex items-center justify-center text-white shadow-lg shadow-red-600/20">
                        <i class="bi bi-file-earmark-text text-2xl"></i>
                    </div>
                    <div class="min-w-0">
                        <div class="flex items-center gap-3 mb-1">
                            <h3 class="text-xl font-black text-gray-900 dark:text-white truncate leading-tight uppercase italic" id="view-quote-number">Q26-0000</h3>
                            <span id="view-quote-status" class="px-3 py-0.5 rounded-full text-[9px] font-black uppercase tracking-widest border border-red-100 bg-red-50 text-red-600 dark:bg-red-900/20 dark:border-red-900/30">Draft</span>
                        </div>
                        <p id="view-quote-address-sub" class="text-[10px] text-gray-400 font-black uppercase tracking-[0.2em] truncate">Property Address Placeholder</p>
                    </div>
                </div>
                <button type="button" class="close-view-quote-modal text-gray-400 hover:text-red-600 p-2 transition-colors">
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>

            <div id="view-quote-modal-content" class="p-8 space-y-10 font-sans overflow-y-auto max-h-[70vh]">

                <?php
                // Project Owner / Generated By Section
                $modalDetailOwnerId = 'quote';
                $modalDetailOwnerTitle = 'Quote Generated By';
                include __DIR__ . '/../ui/modal-detail-owner.php';
                ?>

                <div class="bg-gray-50/50 dark:bg-gray-800/30 p-6 rounded-[2rem] border border-gray-100 dark:border-gray-800">
                    <h3 class="text-xs font-black text-red-600 uppercase tracking-[0.3em] flex items-center gap-2 mb-6">
                        <span class="w-8 h-[2px] bg-red-600"></span>
                        <i class="bi bi-geo-alt-fill"></i> Property Location & Access
                    </h3>
                    <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                        <div class="md:col-span-2">
                            <p class="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Full Address</p>
                            <p id="view-quote-full-address" class="text-sm font-bold text-gray-900 dark:text-white">---</p>
                        </div>
                        <div>
                            <p class="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Postal Code</p>
                            <p id="view-quote-postal-code" class="text-sm font-bold text-gray-900 dark:text-white uppercase">---</p>
                        </div>
                        <div>
                            <p class="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Access Code</p>
                            <div class="flex items-center gap-2">
                                <span class="bg-gray-900 text-white px-2 py-0.5 rounded font-mono text-xs font-bold" id="view-quote-access-code">---</span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="px-2">
                    <h3 class="text-xs font-black text-red-600 uppercase tracking-[0.3em] flex items-center gap-2 mb-6">
                        <span class="w-8 h-[2px] bg-red-600"></span>
                        <i class="bi bi-globe"></i> Jurisdictional Info
                    </h3>
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                        <div class="bg-white dark:bg-gray-800/50 p-5 rounded-2xl border border-gray-100 dark:border-gray-700">
                            <p class="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Country</p>
                            <p id="view-quote-country" class="text-sm font-bold text-gray-900 dark:text-white">---</p>
                        </div>
                        <div class="bg-white dark:bg-gray-800/50 p-5 rounded-2xl border border-gray-100 dark:border-gray-700">
                            <p class="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Region / Province</p>
                            <p id="view-quote-region" class="text-sm font-bold text-gray-900 dark:text-white">---</p>
                        </div>
                        <div class="bg-white dark:bg-gray-800/50 p-5 rounded-2xl border border-gray-100 dark:border-gray-700">
                            <p class="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">City / Municipality</p>
                            <p id="view-quote-city" class="text-sm font-bold text-gray-900 dark:text-white">---</p>
                        </div>
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-10 px-2">
                    <div>
                        <h3 class="text-xs font-black text-red-600 uppercase tracking-[0.3em] flex items-center gap-2 mb-6">
                            <span class="w-8 h-[2px] bg-red-600"></span>
                            <i class="bi bi-file-earmark-pdf-fill"></i> Quote Document
                        </h3>
                        <div class="flex items-center space-x-4 p-5 rounded-2xl bg-gray-950 text-white shadow-xl">
                            <div class="bg-white/10 p-3 rounded-xl">
                                <i class="bi bi-filetype-pdf text-2xl text-red-500"></i>
                            </div>
                            <div class="min-w-0 flex-1">
                                <p class="text-[9px] font-bold text-gray-400 uppercase tracking-widest mb-1">Attached PDF</p>
                                <a id="view-quote-pdf-link" href="#" target="_blank" class="block text-sm font-bold text-red-400 truncate hover:text-red-300 transition-colors">
                                    No Document Attached
                                </a>
                            </div>
                        </div>
                    </div>

                    <div>
                        <h3 class="text-xs font-black text-red-600 uppercase tracking-[0.3em] flex items-center gap-2 mb-6">
                            <span class="w-8 h-[2px] bg-red-600"></span>
                            <i class="bi bi-clock-history"></i> Log History
                        </h3>
                        <div class="space-y-4">
                            <div class="flex items-center justify-between border-b border-gray-50 dark:border-gray-800 pb-2">
                                <span class="text-xs text-gray-500">Date Generated</span>
                                <span id="view-quote-created" class="text-xs font-bold text-gray-900 dark:text-white">---</span>
                            </div>
                            <div class="flex items-center justify-between border-b border-gray-50 dark:border-gray-800 pb-2">
                                <span class="text-xs text-gray-500">Last System Update</span>
                                <span id="view-quote-updated" class="text-xs font-bold text-gray-900 dark:text-white">---</span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="px-8 py-5 border-t border-gray-100 dark:border-gray-800 bg-gray-50/50 dark:bg-gray-800/50 flex justify-end items-center space-x-4">
                <button type="button" class="close-view-quote-modal px-5 py-3 text-xs font-black text-gray-500 uppercase tracking-widest hover:text-gray-900 dark:hover:text-white transition-colors">
                    Dismiss
                </button>
                <button type="button" id="view-quote-print-btn" class="px-6 py-3 text-xs font-black text-gray-900 dark:text-white border border-gray-200 dark:border-gray-700 rounded-xl hover:bg-gray-100 dark:hover:bg-gray-800 transition-all flex items-center gap-2 uppercase tracking-widest">
                    <i class="bi bi-printer"></i>
                    Print
                </button>
                <button type="button" id="view-quote-edit-btn" class="px-8 py-3 text-xs font-black text-white bg-red-600 hover:bg-red-700 rounded-xl transition-all active:scale-95 shadow-lg shadow-red-600/20 flex items-center gap-2 uppercase tracking-widest">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24">
                        <path d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                    </svg>
                    Modify Quote
                </button>
            </div>
        </div>
    </div>
</div>