<?php
// /resources/views/components/quotes/view-quote-modal.php
?>

<style>
    /* Custom Stylish Scrollbar for the Modal Content */
    #view-quote-modal-content::-webkit-scrollbar {
        width: 6px;
    }

    #view-quote-modal-content::-webkit-scrollbar-track {
        background: transparent;
        margin: 10px;
    }

    #view-quote-modal-content::-webkit-scrollbar-thumb {
        background: #cbd5e1;
        border-radius: 10px;
        border: 2px solid transparent;
    }

    .dark #view-quote-modal-content::-webkit-scrollbar-thumb {
        background: #334155;
    }

    #view-quote-modal-content::-webkit-scrollbar-thumb:hover {
        background: #dc2626; /* Red 600 (Primary) */
    }
</style>

<div id="view-quote-modal" class="fixed inset-0 z-50 hidden">
    <div id="close-view-quote-modal-overlay" class="absolute inset-0 bg-gray-950/60 backdrop-blur-sm transition-opacity"></div>

    <div class="fixed inset-0 z-50 flex items-center justify-center p-4">
        <div class="bg-white dark:bg-gray-900 w-full max-w-3xl rounded-[2.5rem] shadow-2xl border border-gray-200 dark:border-gray-800 overflow-hidden transform transition-all animate-in fade-in zoom-in duration-200">

            <div class="px-8 py-6 border-b border-gray-100 dark:border-gray-800 flex items-center justify-between bg-gray-50/50 dark:bg-gray-800/50">
                <div class="flex items-center space-x-5 overflow-hidden">
                    <div id="view-quote-icon-container" class="h-14 w-14 flex-shrink-0 rounded-2xl bg-red-600 flex items-center justify-center text-white shadow-lg shadow-red-600/20">
                        <span id="view-quote-initial" class="text-xl font-black uppercase"></span>
                    </div>
                    <div class="min-w-0">
                        <div class="flex items-center gap-3 mb-1">
                            <h3 class="text-lg font-black text-gray-900 dark:text-white leading-tight uppercase" id="view-quote-number">Q26-0000</h3>
                            <span id="view-quote-status" class="px-3 py-0.5 rounded-full text-[9px] font-black uppercase tracking-widest border border-red-100 bg-red-50 text-red-600 dark:bg-red-900/20 dark:border-red-900/30">Draft</span>
                        </div>
                        <p id="view-quote-address-sub" class="text-[10px] text-gray-400 font-black uppercase tracking-[0.2em] truncate">Property Address Placeholder</p>
                    </div>
                </div>
                <button type="button" class="close-view-quote-modal text-gray-400 hover:text-red-600 p-2 transition-colors">
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>

            <div id="view-quote-modal-content" class="p-8 space-y-10 font-sans overflow-y-auto max-h-[70vh]">

                <?php
                // Project Owner / Generated By Section
                $modalDetailOwnerId = 'quote';
                $modalDetailOwnerTitle = 'Quote Generated By';
                include __DIR__ . '/../ui/modal-detail-owner.php';
                ?>

                <div class="bg-gray-50/50 dark:bg-gray-800/30 p-6 rounded-[2rem] border border-gray-100 dark:border-gray-800">
                    <h3 class="text-xs font-black text-red-600 uppercase tracking-[0.3em] flex items-center gap-2 mb-6">
                        <span class="w-8 h-[2px] bg-red-600"></span>
                        <i class="bi bi-geo-alt-fill"></i> Property Location & Access
                    </h3>
                    <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                        <div class="md:col-span-2">
                            <p class="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Full Address</p>
                            <p id="view-quote-full-address" class="text-sm font-bold text-gray-900 dark:text-white">---</p>
                        </div>
                        <div>
                            <p class="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Postal Code</p>
                            <p id="view-quote-postal-code" class="text-sm font-bold text-gray-900 dark:text-white uppercase">---</p>
                        </div>
                        <div>
                            <p class="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Access Code</p>
                            <div class="flex items-center gap-2">
                                <span class="bg-gray-900 text-white px-2 py-0.5 rounded font-mono text-xs font-bold" id="view-quote-access-code">---</span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-12 gap-10 px-2">
                    <div class="md:col-span-8">
                        <h3 class="text-xs font-black text-red-600 uppercase tracking-[0.3em] flex items-center gap-2 mb-6">
                            <span class="w-8 h-[2px] bg-red-600"></span>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
                                <path d="M5.625 1.5c-1.036 0-1.875.84-1.875 1.875v17.25c0 1.035.84 1.875 1.875 1.875h12.75c1.035 0 1.875-.84 1.875-1.875V12.75A3.75 3.75 0 0 0 16.5 9h-1.875a1.875 1.875 0 0 1-1.875-1.875V5.25A3.75 3.75 0 0 0 9 1.5H5.625Z" />
                                <path d="M12.971 1.816A5.23 5.23 0 0 1 14.25 5.25v1.875c0 .207.168.375.375.375H16.5a5.23 5.23 0 0 1 3.434 1.279 9.768 9.768 0 0 0-6.963-6.963Z" />
                            </svg>
                            Quote Document
                        </h3>
                        <div class="flex items-center space-x-4 p-5 rounded-2xl bg-gray-950 text-white shadow-xl border border-white/5">
                            <div id="view-quote-pdf-icon" class="bg-white/10 p-3 rounded-xl flex-shrink-0">
                                </div>
                            <div class="min-w-0 flex-1">
                                <p class="text-[9px] font-bold text-gray-500 uppercase tracking-widest mb-1">Attached PDF File</p>
                                <a id="view-quote-pdf-link" href="#" target="_blank" class="block text-sm font-bold text-red-400 truncate hover:text-red-300 transition-colors">
                                    No Document Attached
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="md:col-span-4">
                        <h3 class="text-xs font-black text-red-600 uppercase tracking-[0.3em] flex items-center gap-2 mb-6">
                            <span class="w-8 h-[2px] bg-red-600"></span>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
                                <path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25ZM12.75 6a.75.75 0 0 0-1.5 0v6c0 .414.336.75.75.75h4.5a.75.75 0 0 0 0-1.5h-3.75V6Z" clip-rule="evenodd" />
                            </svg>
                            Log History
                        </h3>
                        <div class="space-y-5 bg-gray-50/50 dark:bg-gray-800/50 p-5 rounded-2xl border border-gray-100 dark:border-gray-800">
                            <div class="flex flex-col">
                                <span class="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Date Generated</span>
                                <span id="view-quote-created" class="text-xs font-bold text-gray-900 dark:text-white">---</span>
                            </div>
                            <div class="flex flex-col">
                                <span class="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Last System Update</span>
                                <span id="view-quote-updated" class="text-xs font-bold text-gray-900 dark:text-white">---</span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="px-8 py-5 border-t border-gray-100 dark:border-gray-800 bg-gray-50/50 dark:bg-gray-800/50 flex justify-end items-center space-x-4">
                <button type="button" class="close-view-quote-modal px-5 py-3 text-xs font-black text-gray-500 uppercase tracking-widest hover:text-gray-900 dark:hover:text-white transition-colors">
                    Dismiss
                </button>
            </div>
        </div>
    </div>
</div>